name: Wispbyte Auto Login

on:
  schedule:
    - cron: '0 20 */2 * *'
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Start Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: "*Wispbyte 任务已启动！*\n预计 8–12 分钟完成\n查看: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          format: markdown

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        timeout-minutes: 8
        run: |
          echo "开始安装依赖（预计 3–6 分钟）"
          set -e
          pip install --quiet playwright aiohttp
          playwright install chromium --with-deps
          echo "依赖安装完成"

      - name: Run login script
        timeout-minutes: 6
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          LOGIN_ACCOUNTS: ${{ secrets.LOGIN_ACCOUNTS }}
        run: |
          echo "开始
